services:
  mc-server:
    build: .
    container_name: mc-server
    ports:
      - '${SERVER_PORT}:25565'
    volumes:
      - ./data:/server
    tty: true
    stdin_open: true
    restart: unless-stopped
